### ISSUE TITLE
编译后系统界面停止运行

### ISSUE THREAD

**Issue by qiurigao** [SudaMod/android#13]
需要需改哪里？https://github.com/qiurigao/android_device_vivo_pd1613
`日志：``D` AndroidRuntime: Shutting down VM
05-31 08:37:03.481  7473  7473 E AndroidRuntime: FATAL EXCEPTION: main
05-31 08:37:03.481  7473  7473 E AndroidRuntime: Process: com.android.systemui, PID: 7473
05-31 08:37:03.481  7473  7473 E AndroidRuntime: Theme: themes:{com.tencent.mobileqq=overlay:system}
05-31 08:37:03.481  7473  7473 E AndroidRuntime: android.view.InflateException: Binary XML file line #104: uid=10007 needs permission android.permission.READ_CONTACTS to read lock_screen_owner_info_enabled for user 0
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.View.inflate(View.java:19795)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:925)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3497)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3493)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:631)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:833)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:230)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.ServiceMonitor.-wrap5(ServiceMonitor.java)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: Caused by: java.lang.SecurityException: uid=10007 needs permission android.permission.READ_CONTACTS to read lock_screen_owner_info_enabled for user 0
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.internal.widget.ILockSettings$Stub$Proxy.getBoolean(ILockSettings.java:385)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.internal.widget.LockPatternUtils.getBoolean(LockPatternUtils.java:1173)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.internal.widget.LockPatternUtils.isOwnerInfoEnabled(LockPatternUtils.java:594)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.keyguard.KeyguardStatusView.getOwnerInfo(KeyguardStatusView.java:217)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.keyguard.KeyguardStatusView.updateOwnerInfo(KeyguardStatusView.java:193)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at com.android.keyguard.KeyguardStatusView.onFinishInflate(KeyguardStatusView.java:133)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:844)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
05-31 08:37:03.481  7473  7473 E AndroidRuntime: 	... 19 more
05-31 08:37:03.498  1628  7095 W ActivityManager: Process com.android.systemui has crashed too many times: killing!

**Comment by gesangtome** [comment]
needs permission android.permission.READ_CONTACTS to read lock_screen_owner_info_enabled for user 0

需要权限
