### ISSUE TITLE
nexus 5x上下拉栏的日期/时间显示在同一行上怎么解决？

### ISSUE THREAD

**Issue by maz-1** [SudaMod/android#17]
图片见https://forum.xda-developers.com/nexus-5x/help/how-to-change-clock-style-quick-t3672634
中文下多出农历以后这一行变得很长，完全拉下来后挡住了右边的图标

**Comment by maz-1** [comment]
浏览源码发现，似乎是因为nexus 5x屏幕大，大屏下日期/时间区域的layout不一样
https://github.com/SudaMod/android_frameworks_base/blob/sm-3.1/packages/SystemUI/res/layout-sw410dp/status_bar_alarm_group.xml

**Comment by wuyi-levard** [comment]
你在device下面单独处理一下layout，使用device里的代码就可以了，不需要改动base源码

**Comment by wuyi-levard** [comment]
我也不知道5X是谁在维护，你直接联系维护者比较好

**Comment by maz-1** [comment]
没加农历情况下显示成一行不会遮挡右边的图标，报告给lineageos应该不会被接受吧

**Comment by wuyi-levard** [comment]
应该是不会的，你自己也可以改的啊
