### ISSUE TITLE
更新源码后编译出错

### ISSUE THREAD

**Issue by sbwml** [SudaMod/android#27]
/home/sm-4.1/out/soong/.bootstrap/bin/soong_build  -t -b /home/sm-4.1/out/soong --docs /home/sm-4.1/out/soong/.bootstrap/docs/soong_build.html ./Android.bp
error: hardware/interfaces/camera/device/1.0/default/Android.bp:37:35: unrecognized property "product_variables.lineage.uses_qti_camera_device"
error: hardware/interfaces/camera/provider/2.4/default/Android.bp:29:35: unrecognized property "product_variables.lineage.uses_qti_camera_device"
error: hardware/interfaces/camera/provider/2.4/default/Android.bp:62:35: unrecognized property "product_variables.lineage.uses_qti_camera_device"
[56/56] /home/sm-4.1/out/soong/.bootstrap/bin/soong_build /home/sm-4.1/out/soong/build.ninja
FAILED: /home/sm-4.1/out/soong/build.ninja 
/home/sm-4.1/out/soong/.bootstrap/bin/soong_build  -t -b /home/sm-4.1/out/soong -d /home/sm-4.1/out/soong/build.ninja.d -o /home/sm-4.1/out/soong/build.ninja Android.bp
error: hardware/interfaces/camera/device/1.0/default/Android.bp:37:35: unrecognized property "product_variables.lineage.uses_qti_camera_device"
error: hardware/interfaces/camera/provider/2.4/default/Android.bp:29:35: unrecognized property "product_variables.lineage.uses_qti_camera_device"
error: hardware/interfaces/camera/provider/2.4/default/Android.bp:62:35: unrecognized property "product_variables.lineage.uses_qti_camera_device"
ninja: build stopped: subcommand failed.
17:02:09 soong failed with: exit status 1

#### failed to build some targets (23 seconds) ####

[root@CentOS-Linux-release-7 sm-4.1]#

**Comment by wuyi-levard** [comment]
我看看都更新了啥

**Comment by wuyi-levard** [comment]
你再编译试试
