### ISSUE TITLE
编译sm1.1 出现变量未定义

### ISSUE THREAD

**Issue by qiurigao** [SudaMod/android#5]
libcore/luni/src/main/native/java_lang_System.cpp: In function 'void System_closeLogSockets(JNIEnv*, jclass)':
libcore/luni/src/main/native/java_lang_System.cpp:66:23: error: '__android_log_close' was not declared in this scope
   __android_log_close();
                       ^
build/core/binary.mk:619: recipe for target '/opt/sudamod/out/target/product/m2note/obj_arm/SHARED_LIBRARIES/libjavacore_intermediates/luni/src/main/native/java_lang_System.o' failed
make: *** [/opt/sudamod/out/target/product/m2note/obj_arm/SHARED_LIBRARIES/libjavacore_intermediates/luni/src/main/native/java_lang_System.o] Error 1
make: *** 正在等待未完成的任务....
make: Leaving directory '/opt/sudamod'

#### make failed to build some targets (11:15 (mm:ss)) ####
编译cm却很顺利,难道是我device的问题?

**Comment by 3EleVen** [comment]
sm1.1已经不再维护
