### ISSUE TITLE
编译sm2.0 出现ld returned 1 exit status

### ISSUE THREAD

**Issue by qiurigao** [SudaMod/android#7]
/home/lenovo/sudamod/out/target/product/m2note/obj/STATIC_LIBRARIES/libc_common_                              intermediates/libc_common.a(ndk_cruft.o): In function `dlmalloc_trim':
/home/lenovo/sudamod/bionic/libc/bionic/ndk_cruft.cpp:392: undefined reference t                              o `dlmalloc_trim_real'
collect2: error: ld returned 1 exit status
build/core/shared_library_internal.mk:80: recipe for target '/home/lenovo/sudamo                              d/out/target/product/m2note/obj/SHARED_LIBRARIES/libc_intermediates/LINKED/libc.                              so' failed
make: *** [/home/lenovo/sudamod/out/target/product/m2note/obj/SHARED_LIBRARIES/l                              ibc_intermediates/LINKED/libc.so] Error 1
make: *** Waiting for unfinished jobs....
warning: string 'android_preparing_apk' has no default translation.
warning: string 'android_preparing_apk_obscured' has no default translation.
warning: string 'android_upgrading_apk' has no default translation.
warning: string 'android_upgrading_complete' has no default translation.
warning: string 'android_upgrading_complete_details' has no default translation.
warning: string 'android_upgrading_fstrim' has no default translation.
warning: string 'android_upgrading_starting_apps' has no default translation.
make: Leaving directory '/home/lenovo/sudamod'

**Comment by wuyi-levard** [comment]
环境没装齐？

**Comment by qiurigao** [comment]
@wuyi-ligux 都装好了
